person:
  lastName: testName
  age: 10
  boss: false
  birth: 2019/1/11
  maps:
    key1: value1
    key2: value2
  lists:
    - item1
    - item2
  dog:
    name: test dog
    age: 5


personValid:
  lastName: testName
  age: 10

server:
  port: 8088
  context-path: /crud

spring:
  profiles:
    active: dev
  thymeleaf:
    cache=false
  messages:
    basename: i18n.login
  mvc:
    locale: en_US
    date-format: yyyy-mm-dd
  datasource:
    password: 123123
    username: root
    url: jdbc:mysql://localhost:3306/cloudDB01
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


logging:
  level: trace
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{50} %line %X{UUID} - %m%n"








---
person:
  age: 15
spring.profiles: dev

---
person:
  lastName: testName prod
  age: 10
  boss: false
spring.profiles: prod
