person:
  lastName: testName
  age: 10
  boss: false
  birth: 2019/1/11
  maps:
    key1: value1
    key2: value2
  lists:
    - item1
    - item2
  dog:
    name: test dog
    age: 5


personValid:
  lastName: testName
  age: 10

spring:
  profiles:
    active: dev

---
person:
  age: 15
spring.profiles: dev

---
person:
  lastName: testName prod
  age: 10
  boss: false
spring.profiles: prod
